# Generated by Django 3.1.3 on 2020-11-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
